spring.application.name=parking-account-service
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.url=jdbc:postgresql://localhost:5558/postgres
spring.datasource.username=postgres
spring.datasource.password=2611

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
