spring.application.name=parking-account-service
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.datasource.url=jdbc:postgresql://localhost:5558/postgres
spring.datasource.username=postgres
spring.datasource.password=2611

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=c2VjdXJpdHlLZXlGb3JBdXRoZW50aWNhdGlvbkFuZEF1dGhvcml6YXRpb24K
jwt.expiration=86400000

payments.provider=MOCK
payments.success-url=http://127.0.0.1:4173/payment/success
payments.failure-url=http://127.0.0.1:4173/payment/failure
payments.webhook-secret=

account.top-up.dev-enabled=false
